### ISSUE TITLE
Grouped Bar Chart

### ISSUE THREAD

**Issue by andisugandi** [yvonnegitau/flask-Dashboard#1]
Hi,

Thank you for creating this excellent apps.

I wonder how to implement [Grouped Bar Chart](https://plot.ly/python/bar-charts/#grouped-bar-chart) in the code?

**Comment by yvonnegitau** [comment]
Hello,
Thank you for the feedback. 
For grouped data, replace the value assigned to data in line 24 of FirstDashboard.py with :
data=[
    go.Bar(name='SF Zoo', x=animals, y=[20, 14, 23]),
    go.Bar(name='LA Zoo', x=animals, y=[12, 18, 29])
]
That is all. 
Regards,
Yvonne
