### ISSUE TITLE
📄 Please consider adding a LICENSE file

### ISSUE THREAD

**Issue by hayesall** [yvonnegitau/flask-Dashboard#3]
I stumbled into your blog post and the associated code while trying to do something similar.

Please consider releasing this code under an open source license (https://choosealicense.com/). *Technically everyone who has forked this repository is violating your copyright.*

**Comment by yvonnegitau** [comment]
Thanks for that

**Comment by hayesall** [comment]
No, thank you!

The blog post is really nice too!
